/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QLNV_Frame;

import JFrame_ThemNhanVien.AddNhanVien;
import QLBH_Frame.QLBH;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import service.NhanVienService;

/**
 *
 * @author PC
 */
public class QLNV_Frame extends javax.swing.JFrame {
    NhanVienService nhanVienService ;
    DefaultTableModel defaultTableModel;
    
    /**
     * Creates new form QLBH_Frame
     */
    /**
     * Creates new form QLBH_Frame
     */
    public QLNV_Frame() {
        initComponents();
        
        nhanVienService = new NhanVienService();
        
         defaultTableModel = new DefaultTableModel(){
            @Override// ko cho sua bang
            public boolean isCellEditable(int row, int column) {
                return false;
            }  
        };
        BangNhanVien.setModel(defaultTableModel);
        defaultTableModel.addColumn("MaNhanVien");
        defaultTableModel.addColumn("TenNhanVien");
        defaultTableModel.addColumn("NgaySinh");
        defaultTableModel.addColumn("GioiTinh");
        defaultTableModel.addColumn("CMND");
        defaultTableModel.addColumn("DiaChi");
        defaultTableModel.addColumn("SoDT");
        defaultTableModel.addColumn("Password");
        
        ArrayList <NhanVien> nhanviens = nhanVienService.getAllEmp();
        
        for(NhanVien nhanVien : nhanviens){
            defaultTableModel.addRow(new Object[]{
                nhanVien.getMaNhanVien(),nhanVien.getTenNhanVien(),
            nhanVien.getNgaySinh(),nhanVien.getGioiTinh(),nhanVien.getCMND(),nhanVien.getDiaChi(),
            nhanVien.getSoDT(),nhanVien.getPassword()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Botton_QuayLai = new javax.swing.JButton();
        Text_NhapThongTin = new javax.swing.JTextField();
        ThemNhanVien = new javax.swing.JButton();
        XoaNhanVien = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BangNhanVien = new javax.swing.JTable();
        CapNhatNhanVien = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TimKiem_Botton = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("QUẢN LÍ THÔNG TIN NHÂN VIÊN");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Botton_QuayLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        Botton_QuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botton_QuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Botton_QuayLai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Botton_QuayLai)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Text_NhapThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_NhapThongTinActionPerformed(evt);
            }
        });

        ThemNhanVien.setBackground(new java.awt.Color(255, 255, 102));
        ThemNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ThemNhanVien.setForeground(new java.awt.Color(51, 255, 0));
        ThemNhanVien.setText("Thêm nhân viên");
        ThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemNhanVienActionPerformed(evt);
            }
        });

        XoaNhanVien.setBackground(new java.awt.Color(255, 255, 102));
        XoaNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        XoaNhanVien.setForeground(new java.awt.Color(51, 255, 0));
        XoaNhanVien.setText("Xoá nhân viên");
        XoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XoaNhanVienActionPerformed(evt);
            }
        });

        BangNhanVien.setForeground(new java.awt.Color(207, 148, 16));
        BangNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã nhân viên", "Tên nhân viên", "Ngày sinh", "Giới tính", "CMND", "Địa chỉ", "Số điện thoại", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        BangNhanVien.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        BangNhanVien.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(BangNhanVien);

        CapNhatNhanVien.setBackground(new java.awt.Color(255, 255, 102));
        CapNhatNhanVien.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CapNhatNhanVien.setForeground(new java.awt.Color(51, 255, 0));
        CapNhatNhanVien.setText("Cập nhật");
        CapNhatNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CapNhatNhanVienActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Tìm kiếm nhân viên");

        TimKiem_Botton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TimKiem_Botton.setText("Tìm kiếm");
        TimKiem_Botton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimKiem_BottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Text_NhapThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(TimKiem_Botton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(ThemNhanVien)
                .addGap(93, 93, 93)
                .addComponent(XoaNhanVien)
                .addGap(112, 112, 112)
                .addComponent(CapNhatNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Text_NhapThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(TimKiem_Botton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(CapNhatNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(XoaNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThemNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(167, 167, 167))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemNhanVienActionPerformed
        // TODO add your handling code here:
        new AddNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ThemNhanVienActionPerformed

    private void CapNhatNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CapNhatNhanVienActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        ArrayList <NhanVien> nhanviens = nhanVienService.getAllEmp();
        
        for(NhanVien nhanVien : nhanviens){
            defaultTableModel.addRow(new Object[]{
                nhanVien.getMaNhanVien(),nhanVien.getTenNhanVien(),
            nhanVien.getNgaySinh(),nhanVien.getGioiTinh(),nhanVien.getCMND(),nhanVien.getDiaChi(),
            nhanVien.getSoDT(),nhanVien.getPassword()});
        }
    }//GEN-LAST:event_CapNhatNhanVienActionPerformed

    private void XoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XoaNhanVienActionPerformed
        // TODO add your handling code here:
        int row = BangNhanVien.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(QLNV_Frame.this, "Vui long chon user truoc","Loi", JOptionPane.ERROR_MESSAGE);
        }
        else{
            String MaNhanVien = String.valueOf(BangNhanVien.getValueAt(row, 0));
            
            nhanVienService.XoaNhanVien(MaNhanVien);
            // Cap nhat lai du lieu
             defaultTableModel.setRowCount(0);
             ArrayList <NhanVien> nhanviens = nhanVienService.getAllEmp();
        
        for(NhanVien nhanVien : nhanviens){
            defaultTableModel.addRow(new Object[]{
                nhanVien.getMaNhanVien(),nhanVien.getTenNhanVien(),
            nhanVien.getNgaySinh(),nhanVien.getGioiTinh(),nhanVien.getCMND(),nhanVien.getDiaChi(),
            nhanVien.getSoDT(),nhanVien.getPassword()});
        }
            
        }
    }//GEN-LAST:event_XoaNhanVienActionPerformed

    private void Text_NhapThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_NhapThongTinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_NhapThongTinActionPerformed

    private void TimKiem_BottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimKiem_BottonActionPerformed
        // TODO add your handling code here:
        //List
        String text = String.valueOf(Text_NhapThongTin.getText());
        if(text.length()>0){
            System.out.println(text.length());
            System.out.println(text);
            ArrayList <NhanVien> nhanviens = nhanVienService.TimNhanVien(text);
            //nhanviens
            defaultTableModel.setRowCount(0);
            for(NhanVien nhanVien : nhanviens){
            defaultTableModel.addRow(new Object[]{
                nhanVien.getMaNhanVien(),nhanVien.getTenNhanVien(),
            nhanVien.getNgaySinh(),nhanVien.getGioiTinh(),nhanVien.getCMND(),nhanVien.getDiaChi(),
            nhanVien.getSoDT(),nhanVien.getPassword()});
        }
        }
    }//GEN-LAST:event_TimKiem_BottonActionPerformed

    private void Botton_QuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botton_QuayLaiActionPerformed
        // TODO add your handling code here
        new QLBH().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Botton_QuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(QLBH_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(QLBH_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(QLBH_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(QLBH_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new QLBH_Frame().setVisible(true);
//            }
//        });
//   }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BangNhanVien;
    private javax.swing.JButton Botton_QuayLai;
    private javax.swing.JButton CapNhatNhanVien;
    private javax.swing.JTextField Text_NhapThongTin;
    private javax.swing.JButton ThemNhanVien;
    private javax.swing.JButton TimKiem_Botton;
    private javax.swing.JButton XoaNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
